### ISSUE TITLE
RiveReactNativeViewManager.touchEnded must not be null if I tap and drag on a rive view inside a ScrollView

### ISSUE THREAD

**Issue by tomwilsonsb** [rive-app/rive-react-native#140]
### Description
If i put a rive view inside a react-native ScrollView and then touch and drag on it on iOS, it crashes with the error:

"Argument 1 (NSNumber) of RiveReactNativeViewManager.touchEnded must not be null"

If the view is not inside a scrollview, it is fine.

### Expected behavior
Does not crash

#### Additional context
I dug into the code and little and it seems like when the touchEnd gets called from react-native the event has undefined coordinates, so when it calls `const touchEnded = useCallback<RiveRef[ViewManagerMethod.touchEnded]>(` in `Rive.tsx` it sends null for x and y.

Replacing:

`[x, y]` here with `[x ?? 0, y ?? 0]` seems to make it happy but I'm not sure what other consequences this would have or if tis better to not call it at all in that scenario.

FWIW i'm using Expo 0.45, react native 0.68.2, Xcode 13.4.1

**Comment by zplata** [comment]
Thanks for reporting this @tomwilsonsb! We'll take a look and report back here when we have a fix out.

We have some internals about a few user-interaction listening events, and act on it for Rive-specific purposes with a feature called Listeners; the scroll view logic might be conflicting with this. Appreciate your additional context here!

**Comment by zplata** [comment]
Hey @tomwilsonsb, try it out again on `3.0.41`, we introduced a patch here with a similar solution to what you suggested. Hopefully this solves your issue!

**Comment by tomwilsonsb** [comment]
Thank you it is fixed now 🙏
