### ISSUE TITLE
A group's opacity animation blinks/flashes the original state once hits 100% or 0%

### ISSUE THREAD

**Issue by Frans-L** [rive-app/rive-react-native#159]
### Description

Group's opacity animations aren't working correctly if the animations go from 0 to 100. Once it hits 100, it blinks the original state for one frame. The blinking doesn't happen if the animation goes from e.g. 0-99. This also happens if the animation goes from 100 to 0.

This happens at least with iOS devices (iPhone 12, iOS 16) & emulators. I haven't tried with Android. Using the latest Rive version (https://github.com/rive-app/rive-react-native/pull/149) didn't solve the issue. 

The blinking is noticeable especially when trying to create complicated animations with many groups.

### Provide a Repro

Minimal reproducible demo: A group whose opacity transition from 0 to 100, while the child of the group is animated to move down.   

https://rive.app/community/4584-9302-bug-flas

### Video

1 frame blinking happens right after the moving red bar hits opacity level 100. So it happens at the beginning of the video. It's easier to see when playing it at 0.25 playback speed. (Github's video player might skip 1 frame to play it smoothly. I recommend downloading the video offline to see the blinking.)

https://user-images.githubusercontent.com/29607206/224442602-530c3502-8ba2-48aa-8a30-e4aefdd9ead9.mp4

### Versions

Node: 16
React-Native: 0.70
xCode: 14.2

**Comment by Frans-L** [comment]
This seems to happen also with e.g. Google Chrome when watching a preview from _rive.app/community_. I would guess that could affect all platforms from the web to native mobile apps.

I know you @mjtalbot are really busy with all the things. Do you have any rough estimation of when someone could have time to look at this?

**Comment by HayesGordon** [comment]
Hi @Frans-L thanks for reporting this and apologies for not getting back to you sooner. I'm able to reproduce and we'll investigate.

**Comment by zplata** [comment]
Sorry for the delay in getting back here, @Frans-L! This should be fixed in `v4.1.0` and up.
