### ISSUE TITLE
rive-react-native does not work in React Native 0.71.4

### ISSUE THREAD

**Issue by ashuvssut** [rive-app/rive-react-native#166]
I tried this example code block from the docs. I use React Native 0.71.4. It is showing blank (no animation)

I tried loading a local resource. still nothing.
```js
<Rive
  url="https://public.rive.app/community/runtime-files/2195-4346-avatar-pack-use-case.riv"
  artboardName="Avatar 1"
  stateMachineName="avatar"
  style={{ width: 400, height: 400 }}
/>
```

**Comment by ashuvssut** [comment]
@ahmaddehnavi Can you tell me exactly which version should I use in v3?
Which one are you using? latest of v3 ([3.0.41](https://github.com/rive-app/rive-react-native/releases/tag/v3.0.41))?

**Comment by ahmaddehnavi** [comment]
> @ahmaddehnavi Can you tell me exactly which version should I use in v3? Which one are you using? latest of v3 ([3.0.41](https://github.com/rive-app/rive-react-native/releases/tag/v3.0.41))?
> 
> I am using lottie right now... but I wanted to try rive
Yeah, v3.0.41 works for me

غثشا

**Comment by HayesGordon** [comment]
Hi! We're looking into this? Are you experiencing the blank window on Android?

**Comment by ashuvssut** [comment]
@HayesGordon yes. I used an android physical device

I also tried doing gradle clean, deleting the node_modules yarn.lock and then reinstalling it. Then the animation showed up for the first time. But after that when I reloaded there was no animation. It was blank. I ran build again. Still blank. Then I have to rely on lottie. I will try older v3 version tho

**Comment by T-Damer** [comment]
Same for me, it loads only once sometimes and then disappears no matter if you use `url` or `resourceName`

**Comment by zplata** [comment]
Hi all - can you try on `v4.0.1`? We had some underlying `rive-android` native fixes we ported over to the bridge here in this new version and it may help with some of the rendering issues.

**Comment by ashuvssut** [comment]
@zplata `v4.0.1` fixes it. Thanks
