### ISSUE TITLE
Version 4 does not work on Android

### ISSUE THREAD

**Issue by tobob** [rive-app/rive-react-native#168]
It simply does not display any asset - both provided by URL and asset `main/res/raw`
component is in place but, nothing shows in this area 

device: Blackview A70 - 11
Android version: 11
react-native: 0.70.6

It works on version 3.0.41 and iOS (on iOS version 4 works well)

**Comment by Pandan** [comment]
I've also experienced the same issue, where the animation stopped working on Android. 
Currently, I'm using 'react-native' version 0.71.5. 
I also found that switching back to version 3.0.41 resolved the problem for me.

**Comment by zplata** [comment]
Hi! We've got a fix coming in soon in a patch - sorry for the issues here.

https://github.com/rive-app/rive-react-native/pull/169
