### ISSUE TITLE
Events not triggered

### ISSUE THREAD

**Issue by wibimaster** [rive-app/rive-react-native#170]
### Description
Event is not triggered

### Provide a Repro
```
        <Rive
          ref={riveRef}
          resourceName="xxx"
          artboardName="XXX"
          animationName="xXx"
          fit={Fit.Fill}
          autoplay={false}
          onStateChanged={(sm, n) => {
            console.log('state changed', sm, n);
          }}
          onPlay={(an, ism) => {
            console.log('play', an, ism);
          }}
          onPause={(an, ism) => {
            console.log('pause', an, ism);
          }}
          onStop={(an, ism) => {
            console.log('stop', an, ism);
          }}
          onLoopEnd={(an, ism) => {
            console.log('loop end', an, ism);
          }}
          onError={(err) => {
            console.log('error', err);
          }}
        />

// [...]
      riveRef.current?.play(
        'xXx',
        LoopMode.Auto,
        Direction.Auto,
        false,
      );
```

### Expected behavior
At least "onPlay" and "onLoopEnd" should be triggered

### Device & Versions (please complete the following information)
- Device: Mi 11
- OS: Android 12
- NPM Version: 9.5.0

**Comment by HayesGordon** [comment]
I'll take a look into this and update soon 👍

**Comment by Jenyfair** [comment]
Same problem for me. 
Using "react-native": "0.70.6" and "rive-react-native": "4.0.2"
Works ok on ios but can seem to trigger any event on Android device

**Comment by HayesGordon** [comment]
Thanks for reporting everyone. We can reproduce it our end, and this is resolved with the latest version of the Android runtime. We're working on a few other fixes and will release a new version of RN soon

**Comment by zplata** [comment]
Sorry all! The merged PR to fix this closed this issue a bit prematurely - do you mind testing the eventing on `4.0.4`?
