### ISSUE TITLE
iOS joystick animation not working

### ISSUE THREAD

**Issue by jeremybarbet** [rive-app/rive-react-native#187]
### Description

Hi,

I have the following rive animation using joysticks and I'm trying to integrate it using the react-native runtime.

According to the [documentation](https://help.rive.app/runtimes/feature-support#joystick-support) it's already supported. However, I'm using `"rive-react-native": "4.1.2"` and it doesn't work on iOS. It works just fine on Android.

### Provide a Repro

I'm using [this method](https://help.rive.app/runtimes/overview/react-native/loading-in-rive-files#option-2-asset-bundle) to load the files on iOS and Android.

It works fine for any other animations but not Joystick on iOS.

```tsx
const SomeScreen = () => {
  return (
    <Rive style={{ width: 100, height: 100 }} resourceName="bell_joysticks" />
  );
}
```

#### Source `.riv`/`.rev` file
[joystick.zip](https://github.com/rive-app/rive-react-native/files/11936967/joystick.zip)

### Expected behavior
To work the same as Android

#### Screenshots

iOS:
(An image, because the animation doesn't play)

![Screenshot 2023-07-03 at 12 53 00](https://github.com/rive-app/rive-react-native/assets/937328/7f6d842d-599a-4c37-9449-ba2718fce73f)

Android:

https://github.com/rive-app/rive-react-native/assets/937328/2b610ec1-79ee-41e9-b3e2-5799570a7dba

### Device & Versions (please complete the following information)
- Device: iOS simulator
- OS: iOS 16.4
- NPM Version: npm `9.3.1`, yarn `1.22.19`

**Comment by zplata** [comment]
Hi @jeremybarbet - there's an issue we're working to fix on default behavior on iOS and Android (i.e., playing a default animation vs state machine) so apologies that you're seeing differing behavior at the moment!

Are you meaning to play the state machine? Or just the animation? It looks like Android is playing the `Timeline 1` animation. I'd recommend specifying what you want Rive to play - so in this case, potentially setting `animationName: "Timeline 1"` on the Rive component.

**Comment by jeremybarbet** [comment]
I meant to play the animation itself.

Indeed the issue was the missing "Timeline 1". It definitely got me confused because it was working on Android by default without specifying the name.

What will be the default behavior once its fixed?

**Comment by zplata** [comment]
@jeremybarbet - The default will be the state machine runs by default (or what you were seeing on iOS). In your rive file, you'd want to set the state machine to use the `Timeline 1` animation in that case.
