### ISSUE TITLE
App is crashing on iOS

### ISSUE THREAD

**Issue by Prakunj** [rive-app/rive-react-native#188]
As soon as iOS app is launched, it gets crashed. I guess something is wrong with resourceName. I am attaching screenshot below

<Rive
    fit={Fit.Contain}
    alignment={Alignment.Center}
    style={{width: '100%',
    height: 600,}}
    resourceName={'skills_listener'}
  />

<img width="1074" alt="Screenshot 2023-07-04 at 5 08 38 PM" src="https://github.com/rive-app/rive-react-native/assets/18291162/45ede15b-26d0-40cf-8ca8-e6b31896c000">

**Comment by HayesGordon** [comment]
Hi @Prakunj, have you included the `skills_listener.riv` file as a resource?

See the docs here for more information on how to do this for iOS and Android: https://help.rive.app/runtimes/overview/react-native/loading-in-rive-files

**Comment by Prakunj** [comment]
Hi @HayesGordon, thanks for helping me :)

**Comment by HayesGordon** [comment]
You're welcome! Closing this issue
