### ISSUE TITLE
rive_react_native/RiveReactNativeView.swift:225: Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value

### ISSUE THREAD

**Issue by Waltari10** [rive-app/rive-react-native#218]
### Description
Upgraded rive-react-native to 6.2.0 from 3.0.41 and now it's crashing the entire app all the time.

Error message in Xcode is: 
`rive_react_native/RiveReactNativeView.swift:225: Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value`

### Provide a Repro

```
import Rive from "rive-react-native";
<Rive resourceName="timeline" stateMachineName="ToggleIcon" />

```
#### Source `.riv`/`.rev` file
- https://rive.app/s/ItJJg8vBUEK3uyPsWdf4IQ/ 
- RIV file: https://drive.google.com/file/d/10hLVLJuOVAkGA6cgBc_y_KNBpaP90WQ6/view?usp=sharing
- REV file: https://drive.google.com/file/d/12EJbRPUl-ckP-bkeFydWgFoyr9niVAU1/view?usp=sharing

### Expected behavior
I'd expect it not to start crashing when updating the package.

#### Screenshots
-

### Device & Versions (please complete the following information)

- Device: iOS simulator iPhone SE (3rd generation)
- OS: iOS 17.2
- NPM Version: 10.1.0

#### Additional context
- I tried upgrading the Rive app to latest version and re-exporting the riv file, but it didn't help.
- Also removed and updated node_modules and pods a few times as well as tried rebuilding the iOS app.

**Comment by Waltari10** [comment]
This PR seems to fix the issue for me: https://github.com/rive-app/rive-react-native/pull/206

**Comment by HayesGordon** [comment]
Hi Waltari, thanks for verifying. Would you happen to have a reproducible example project you can share with us? I'm not able to verify the issue on my side.

The same with the linked issue. But in the meantime we can get that linked PR merged as it seems to solve multiple issues

**Comment by HayesGordon** [comment]
The above PR is merged. I'm closing this issue, but please reopen it if it's not fixed.
