### ISSUE TITLE
[Question]  What happens if I give undefined for a Rive file without a stateMachineName?

### ISSUE THREAD

**Issue by WooMinGy** [rive-app/rive-react-native#227]
![image](https://github.com/rive-app/rive-react-native/assets/86763219/9ff3bd3c-c879-4008-90c9-4b83f1568ac9)

I am encapsulating the Rive component for use.  (Like the image above)
Naturally, I pass the stateMachineName as props to the Rive Component. 
If I don't specify a stateMachineName in the Rive file and end up passing the file's URL with stateMachineName set to undefined, could this lead to unexpected errors?

Because I detected the error in the photo below through Sentry. (Only iOS)
<img width="831" alt="image" src="https://github.com/rive-app/rive-react-native/assets/86763219/6e25bd31-5cb1-4875-b9de-7eb05ecf008d">

**Comment by HayesGordon** [comment]
Hi @WooMinGy , I always recommend setting the state machine name explicitly. As the default may unintentionally change when modifying the animation in the editor, or new artboards may be added, etc.

If you do not give the StateMachine name (or no animation name), then the defaults will be played as set in the editor (I need to confirm that Android does, in fact, play the default but iOS does). Either way, I would still set the **state machine name** and **artboard name** through code.

With the error you shared above, it seems like this particular artboard does not have a state machine name `State Machine 1`

**Comment by WooMinGy** [comment]
Thank you for your response. 
After hearing what you said, we checked all of our team's Rive files and confirmed that if the stateMachineName is not specified, it defaults to having the name 'State Machine 1'. 
We will make sure to explicitly set the stateMachineName for all of them and monitor the situation!
I'm gonna close the issue, thanks!
