### ISSUE TITLE
New rive-react-native release with latest Native packages

### ISSUE THREAD

**Issue by Waltari10** [rive-app/rive-react-native#228]
Hi,

I'm wondering if we could have a new react native Rive release with the latest native packages?

Currently there is a few crashes we are experiencing in our app, that are fixed by the native upgrades. We have a hacky patch package solution in place, but would be nice to have a official update as well. Thanks!

**Comment by HayesGordon** [comment]
The latest version is now available with v7.0.0 - there are no breaking changes in RiveReactNative. But it is a major bump as the underlying iOS and Android runtimes have undergone bigger changes.

Closing this issue. Please reopen if you're still encountering problems.
