### ISSUE TITLE
Rive crashes on 2 devices Samsung Galaxy A13 5G and Motorola moto g pure

### ISSUE THREAD

**Issue by AChevallier** [rive-app/rive-react-native#230]
Hello,

My problem is simple because it has been fixed in the lastest version of rive-android.

My issue is https://github.com/rive-app/rive-android/issues/308

I would like to know when it would be available for [rive-react-native](https://github.com/rive-app/rive-react-native)

Thank you

**Comment by HayesGordon** [comment]
Hi @AChevallier, we're working on resolving an issue and providing new features that will enable Rive React Native to use the latest versions of Rive Android and Rive iOS. Work is underway and we'll update here.

**Comment by LeDanielH** [comment]
We temporarily resolved the issue by downgrading. 
<img width="232" alt="Screenshot 2024-04-02 at 21 10 29" src="https://github.com/rive-app/rive-react-native/assets/10798542/95c78427-23cb-4c8b-9335-62b317c6cc94">. Thank you.

**Comment by HayesGordon** [comment]
Latest version is now published, v7.0.0. This is a major release, but there are no breaking changes in Rive ReactNative, however the underlying iOS and Android runtimes have undergone bigger changes. Please reopen this issue if you're still encountering difficulties.
