### ISSUE TITLE
How do I call a nested artboard input

### ISSUE THREAD

**Issue by acominotto** [rive-app/rive-react-native#242]
Hello,

We have a rather complicated rive file that includes some nested artboard whose inputs are exposed in the main artboard.

But we cannot find how to set them

we tried: 

`riveRef.setInputState('State Machine', 'NestedArtboard Symbol', 1)`
where NestedArtboard is the name of the input and Symbol is the name of the input within the artboard

----

`riveRef.setInputState('State Machine', 'NestedArtboard Symbol', 1)`
where 'NestedArtboard Symbol' is the name of the input within the artboard.

Is there not a way to achieve setting a nested artboard input ? I cannot find it anywhere in the documentation.

Thanks in advance

**Comment by HayesGordon** [comment]
Hi, this is not exposed, but we're looking to expose it soon!

**Comment by HayesGordon** [comment]
This is now supported on the latest version! See our docs: https://rive.app/community/doc/state-machines/docxeznG7iiK#nested-inputs
