### ISSUE TITLE
cannot take  android development build in expo

### ISSUE THREAD

**Issue by sarathchandt** [rive-app/rive-react-native#256]
rive was working fine when i use the version 6.2.1 and now i updated to 7.3.0 to  select the renderer. And now i can test on ios by using the xcode. But while testing on android with android studio i am getting error

* What went wrong:
Execution failed for task ':app:mergeExtDexDebug'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform rive-android-9.5.1.aar (app.rive:rive-android:9.5.1) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.category=library, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=androidJvm}.
      > Execution failed for DexingWithClasspathTransform: /Users/mac/.gradle/caches/transforms-3/da8a350e9a031ed20fca585d19120785/transformed/jetified-rive-android-9.5.1-runtime.jar.
         > Error while dexing.
   > Failed to transform kotlin-reflect-1.9.22.jar (org.jetbrains.kotlin:kotlin-reflect:1.9.22) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for DexingWithClasspathTransform: /Users/mac/.gradle/caches/transforms-3/77e4433cab7ff4067492c3bd345df444/transformed/jetified-kotlin-reflect-1.9.22.jar.
         > Error while dexing.
   > Failed to transform kotlin-stdlib-1.9.22.jar (org.jetbrains.kotlin:kotlin-stdlib:1.9.22) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.category=library, org.gradle.jvm.environment=standard-jvm, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=jvm}.
      > Execution failed for DexingWithClasspathTransform: /Users/mac/.gradle/caches/transforms-3/b95347fafd157212fbd727f09bc4f8f2/transformed/jetified-kotlin-stdlib-1.9.22.jar.
         > Error while dexing.

* Try:

**Comment by deepanshushukla** [comment]
@sarathchandt how did you fix this issue , I am also facing the same.
