### ISSUE TITLE
Manifest merger failed due to incompatible minSdkVersion assembleDebug for detox

### ISSUE THREAD

**Issue by RemyNtshaykolo** [rive-app/rive-react-native#269]
Hi there, 

I'm encountering an issue when trying to build my project for detox using the command `./gradlew assembleDebug assembleAndroidTest -DtestBuildType=debug`. The build process fails with the following error:

```
Execution failed for task ‘:rive-react-native:processDebugAndroidTestManifest’.

	Manifest merger failed : uses-sdk:minSdkVersion 21 cannot be smaller than version 23 declared in library [com.facebook.react:react-android:0.74.5] /Users/hidden_path/.gradle/caches/8.8/transforms/4cdf2579b3c60d835b578bdaa2429cde/transformed/jetified-react-android-0.74.5-debug/AndroidManifest.xml as the library might be using APIs not available in 21
Suggestion: use a compatible library with a minSdk of at most 21,
or increase this project’s minSdk version to at least 23,
or use tools:overrideLibrary=“com.facebook.react” to force usage (may lead to runtime failures)
```

**Steps to Reproduce:**

1. Run the command: `./gradlew assembleDebug assembleAndroidTest -DtestBuildType=debug`.
2. Observe the error regarding `minSdkVersion`.

**Expected Behavior:**

The build should complete successfully without any manifest merger errors.

**Actual Behavior:**

The build fails due to a conflict in `minSdkVersion` between the project and the `react-android` library.

**Possible Solutions:**

- Update the project's `minSdkVersion` to at least 23 in the `build.gradle` file.
- Use a compatible library with a `minSdkVersion` of at most 21.
- Use `tools:overrideLibrary="com.facebook.react"` in the manifest, but this may lead to runtime failures.

**Environment:**

- React Native version: 0.74.5

**Comment by RemyNtshaykolo** [comment]
Hi there.
I find a hack to prevent the error from happening by excluded the rive related tasks. 
``` 
./gradlew assembleDebug assembleAndroidTest -DtestBuildType=debug -x rive-react-native:processDebugAndroidTestManifest -x rive-react-native:processDebugAndroidTestResources -x rive-react-native:mergeDebugAndroidTestNativeLibs -x rive-react-native:packageDebugAndroidTest"
```
With that command I can successfully build the my androidTest.apk file and run my detox tests smoothly.

**Comment by aecorredor** [comment]
We ran into this exact problem, but only locally in some dev machines. In Expo EAS we haven't seen this error.
